//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIACBibliotecaClases
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATOS
    {
        public decimal ID { get; set; }
        public System.DateTime FECHAINICIO { get; set; }
        public System.DateTime FECHAFIN { get; set; }
        public decimal CLIENTE { get; set; }
        public decimal EMPRESA { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
    }
}
